---
- hosts: prod
  sudo: yes

  roles:
    - ansible-jenkins

  tasks:
    - apt: update_cache=yes
    - apt: name=openjdk-7-jdk
    - apt: name=maven
    - apt: name=curl

    - command: curl -sL 'https://deb.nodesource.com/setup_0.12 | sudo bash -'
    - apt: name=nodejs
    - npm: name=grunt-cli global=yes