---
- hosts: prod
  sudo: yes

  roles:
    - ansible-jenkins

  tasks:

    - name: Assign jenkins user to the sudo group
      user: name=jenkins state=present groups="jenkins,sudo"

    - name: Install server packages required by project
      apt: update_cache=yes
      apt: name=openjdk-7-jdk
      apt: name=maven
      apt: name=curl

    - name: Install Node 0.12
      command: curl -sL 'https://deb.nodesource.com/setup_0.12 | sudo bash -'
      apt: name=nodejs
      npm: name=grunt-cli global=yes

    - name: Ensure applications can be run without sudo password
      apt: name=libcap2-bin
      command: setcap cap_net_bind_service=+ep /usr/bin/nodejs
      command: setcap cap_net_bind_service=+ep /usr/bin/pgrep

    - name: Create directory for the source code to live
      file: path=/var/www/SizeGuideTester state=directory owner=jenkins group=jenkins mode=0775 recurse=yes